### ISSUE TITLE
How to modify colour scales?

### ISSUE THREAD

**Issue by JasperGattiker** [lazappi/clustree#100]
Hello, 
I'm using :

clustree(DataFrame_clust, node_colour = "SOX2",  node_colour_aggr = "mean") + scale_color_continuous("red","blue")
or
clustree(DataFrame_clust, node_colour = "SOX2",  node_colour_aggr = "mean") + scale_color_continuous(c("red","blue"))

to look at the mean expression of, for example, Sox2 in the clustree estimated clusters. I'd like to set the color scale for mean gene expression to have a warm color and a cool color as the high and low indicators, since it's easier for me in interpretation, rather than having 2 shades of blue (which I admit is more aesthetically pleasing). 

Neither of the lines I pasted above changed the color of the nodes. The top line removed that scale in the legend entirely, and the bottom line just changed the title of the color scale to "red" without actually changing the colors. 

Am I using the wrong color modifier here? Even if I am, when specifying a color scale, how do I ensure I'm adjusting the colors for the correct element? Nodes, edges, text, etc can all have aesthetics modified, if I understand correctly, so how can I link the color modifier I want to work with, especially if I'm modifying multiple elements?

**Comment by lazappi** [comment]
Hi @JasperGattiker 

Colour scales are controlled using the `scale_colour_*` functions in the **{ggplot2}** package for nodes or the `scale_edge_colour_*` functions in the **{ggraph}** package for edges.

I think the problem in your example is that you are using `scale_colour_continuous()` when you need `scale_colour_gradient()`. Here is an example using the example dataset:

```r
clustree(nba_clusts, prefix = "K", node_colour = "ReboundPct",
         node_colour_aggr = "mean") +
    scale_colour_gradient(low = "red", high = "blue")
```

![image](https://github.com/lazappi/clustree/assets/6869320/27984663-7017-40a0-a96f-8cde81f29cc7)

There are lots of examples around explaining these scale functions and how to get different kinds of palettes so I would suggest looking around to find something that matches what you would like.

**Comment by JasperGattiker** [comment]
@lazappi  Thank you very much! I get tripped up by all the ggplot2 options all the time.
