### ISSUE TITLE
Difference between `size` and `count` when plotting gene expression level

### ISSUE THREAD

**Issue by denvercal1234GitHub** [lazappi/clustree#101]
Hi there, 

Thanks for the package. 

Would you mind clarifying the difference between `count`, `size` and `in_prop` when showing the gene expression level as color for the nodes?

Thank you for your help!

**Comment by lazappi** [comment]
`size` is related to how big the nodes are. By default it is the number of samples in each node but it can be set to something else. `count` and `in_prop` refer to properties of edges. `count` is the number of samples associated with an edge and `in_prop` is a ratio between the number of samples in the lower resolution node (the root of the edge) and the number of samples in the edge. It is designed to give an idea of the importance of each node.

Please see the function documentation and paper for more details.
