### ISSUE TITLE
Round node_label_aggr output

### ISSUE THREAD

**Issue by smith6jt-cop** [lazappi/clustree#103]
Hello,

Apologies if this is due to my lack of R knowledge, but is it possible to keep the node label calculations as whole numbers?  Even with whole number input, I am getting a decimal output with 13 places.  Not sure if this is something to change in R Studio or clustree.  Any help would be appreciated.  Thanks for making clustree!

Best,

Justin

**Comment by lazappi** [comment]
This should be possible by adjusting the function you are using. Can you please provide an example of what you are trying to do using one of the datasets in the package?

**Comment by lazappi** [comment]
@smith6jt-cop I am going to close this issue. Please reopen/comment if you need further help.
