### ISSUE TITLE
Showing sample percentage

### ISSUE THREAD

**Issue by lazappi** [lazappi/clustree#12]
Originally from blog comment: http://disq.us/p/1rqks3t

Hi,

If the clusters are originating from two different samples, is there a way to integrate the percentage of cells in each cluster at each resolution in this tree?

Thanks,

Bibaswan

**Comment by lazappi** [comment]
Hi Bibaswan

In the package version of the clustree function you can supply functions to change the aesthetics of the cluster nodes. I think this will do something like what you want:

``` r
library("clustree")
df <- data.frame(Sample = c("A", "A", "B", "B"),
                             Res0 = c(0, 0, 0, 0),
                             Res1 = c(0, 0, 1, 1),
                             Res2 = c(0, 1, 1, 2))

sample_prop <- function(x) {(sum(x == "A") / length(x)) * 100}

clustree(df, prefix = "Res", node_colour = "Sample", node_colour_aggr = "sample_prop")
```

Let me know if you have any more questions

**Comment by ghoshal** [comment]
Hi,

I am running the clustree on a single cell dataset. So each sample technically is each cell. However, in my case the cells are from two different samples. Have a look below. Please let me know if I can incorporate this information on the tree.
<img width="540" alt="screen shot 2018-04-16 at 2 11 20 pm" src="https://user-images.githubusercontent.com/11318165/38827196-213966a2-4180-11e8-9ffd-d2fc886a2a52.png">

**Comment by lazappi** [comment]
That looks like a Seurat object so you should be able to something similar by passing that to the `clustree` function as shown in the vignette:

``` r
seurat # Your Seurat object
sample_col # Name of the column containing sample information
sample_name # Name of the sample you want to plot the proportion of

sample_prop <- function(x) {(sum(x == sample_name) / length(x)) * 100}
clustree(seurat, node_colour = sample_col, node_colour_aggr = "sample_prop")
```

**Comment by lazappi** [comment]
Thanks! Feel free to open a new issue if you have any other questions.
