### ISSUE TITLE
ERROR in examples

### ISSUE THREAD

**Issue by LuyiTian** [lazappi/clustree#13]
running:
```
library(clustree)
data("iris_clusts")
clustree(iris_clusts, prefix = "K")
```

gives me an error:
```
Error in guide_train.edge_colourbar(guide, scale, output) : 
  unused argument (output)
```

Is it due to incompatible versions?

this is my session info:

> 
> attached base packages:
> [1] stats     graphics  grDevices utils     datasets  methods   base     
> 
> other attached packages:
> [1] bindrcpp_0.2       clustree_0.1.2     ggraph_1.0.1       ggplot2_2.2.1.9000
> 
> loaded via a namespace (and not attached):
>  [1] Rcpp_0.12.16       pillar_1.1.0       compiler_3.4.3     git2r_0.21.0       plyr_1.8.4         bindr_0.1          viridis_0.5.1     
>  [8] tools_3.4.3        digest_0.6.15      checkmate_1.8.5    viridisLite_0.3.0  memoise_1.1.0      tibble_1.4.2       gtable_0.2.0      
> [15] pkgconfig_2.0.1    rlang_0.2.0        igraph_1.2.1       curl_3.2           ggrepel_0.8.0.9000 yaml_2.1.16        gridExtra_2.3     
> [22] withr_2.1.2        dplyr_0.7.4        httr_1.3.1         knitr_1.19         devtools_1.13.5    grid_3.4.3         glue_1.2.0        
> [29] R6_2.2.2           tweenr_0.1.5       udunits2_0.13      magrittr_1.5       backports_1.1.2    scales_0.5.0       MASS_7.3-48       
> [36] units_0.5-1        assertthat_0.2.0   ggforce_0.1.1      colorspace_1.3-2   labeling_0.3       lazyeval_0.2.1     munsell_0.4.3

**Comment by lazappi** [comment]
Hi @LuyiTian 

Thanks for checking out clustree. I'm not sure what could be causing that issue. The `guide_train.edge_colourbar` function is in `ggraph`, but I am using the same version and don't have any problems. I do have a slightly different version of `bindrcpp` (v0.2.2) but I can't think why that would make any difference.

Can you maybe print some more of the error trace, that might help us find what is calling the function? You might need to use `traceback()`.

**Comment by mmarczyk363** [comment]
Hi @lazappi 

I've got the same error, when running the same example using Iris dataset. I have the latest versions of bindrcpp (0.2.2), clustree (0.1.2), ggraph (1.0.1) and ggplot2 (2.2.1.9000).

The error trace is below:
```
7: guide_train(guide, scale, output)
6: guides_train(scales = scales, theme = theme, guides = guides, 
       labels = labels)
5: build_guides(plot$scales, plot$layers, plot$mapping, position, 
       theme, plot$guides, plot$labels)
4: ggplot_gtable.ggplot_built(data)
3: ggplot_gtable(data)
2: print.ggplot(x)
1: function (x, ...) 
   UseMethod("print")(x)
```

Michal

**Comment by lazappi** [comment]
You are correct, this is related to the upcoming new version of ggplot2. The current release of clustree (v0.1.2) on CRAN is designed to be compatible with the current CRAN version of ggplot2 (v2.2.1). There will be a new release of clustree in the coming days that will be compatible with the upcoming new version of ggplot2 (v2.3.0).

If you want to use the development version of ggplot2 (v.2.2.1.9000) now you will also need to install the development version of ggraph (v1.0.1.9999) and clustree (v0.1.2.9003), but please be aware that there are always risks of incompatibilities when using development versions.
