### ISSUE TITLE
Producing clustering trees from seurat 

### ISSUE THREAD

**Issue by lmacdonald12** [lazappi/clustree#18]
Hello, 

Well done on the release of your package! 
I am using it to produce a clustering tree from a Seurat object. However, the tree I produce is quite simple as there seems to only be 2 resolutions. I was looking at your example for Seurat here (https://lazappi.github.io/clustree/articles/clustree.html) and your metadata contains clustering for a variety of resolutions. Do you know how I go about fixing this? I realize this isn't an issue directly associated with clustree & perhaps more so Seurat. I was just wondering if you knew how I could visualize the clustering at more resolutions than just 0.6 and 0.8. 

Cheers in advance, 
Lucy

```
pbmc <- FindClusters(object = pbmc, reduction.type = "pca", dims.use = 1:10, print.output = 0, save.SNN = TRUE)
PrintFindClustersParams(object = pbmc)
Parameters used in latest FindClusters calculation run on: 2018-07-20 23:27:12
=============================================================================
Resolution: 0.6
-----------------------------------------------------------------------------
Modularity Function    Algorithm         n.start         n.iter
     1                   1                 100             10
-----------------------------------------------------------------------------
Reduction used          k.param          prune.SNN
     pca                 30                0.0667
-----------------------------------------------------------------------------
Dims used in calculation
=============================================================================
1 2 3 4 5 6 7 8 9 10
```
```
head(pbmc@meta.data)
                 nGene nUMI  orig.ident percent.mito res.0.6 res.0.8
AAACCTGAGCATCATC   871 2394 10X_PBMC_8k   0.03844547       6       6
AAACCTGAGCTAACTC   806 1694 10X_PBMC_8k   0.05726092       5       5
AAACCTGAGCTAGTGG  1316 4520 10X_PBMC_8k   0.01946903       3       3
AAACCTGCACATTAGC   898 2788 10X_PBMC_8k   0.01398852       0       1
AAACCTGCACTGTTAG  1526 4667 10X_PBMC_8k   0.03622722       4       4
AAACCTGCATAGTAAG  1495 4440 10X_PBMC_8k   0.03806306       4       4
clustree(pbmc)
```
![screen shot 2018-07-21 at 15 22 48](https://user-images.githubusercontent.com/40166451/43036446-01d3c4b8-8cfa-11e8-8d38-cf8a85e7246f.png)

**Comment by leonfodoulian** [comment]
Hi Lucy,

You should first compute clustering with a range of resolutions using `Seurat` before being able to visualize them with `clustree`. If these data are not present in your `object@meta.data` in the corresponding `Seurat` object, `clustree` will not be able to display them.

Best,
Leon

**Comment by lmacdonald12** [comment]
Hi Leon,

Cheers for your reply! Do you mean manually at each resolution or do you happen to know if there is a parameter where you can do this in the FindCluster function of Seurat?

Cheers again,
Lucy

On 22 Jul 2018, at 00:00, Leon Fodoulian <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi Lucy,

You should first compute clustering with a range of resolutions using Seurat before being able to visualize them with clustree. If these data are not present in your object@meta.data<mailto:object@meta.data> in the corresponding Seurat object, clustree will not be able to display them.

Best,
Leon

**Comment by leonfodoulian** [comment]
Hi Lucy,

You can use the following:

```R
# Select a range of resolutions
resolution.range <- seq(from = 0, to = 1, by = 0.2)

# Find clusters using a range of resolutions
object <- Seurat::FindClusters(object = object, resolution = resolution.range)
```

Best,
Leon

**Comment by lazappi** [comment]
Thanks for the reply @leonfodoulian! I think this is a good answer to this question so I am going to close the issue but feel free to open a new one if you have any questions @lmacdonald12 and thanks for giving clustree a go!
