### ISSUE TITLE
Two-argument feature and classic clustree labels

### ISSUE THREAD

**Issue by BioSok** [lazappi/clustree#23]
Hi,
Great work on the package! I was wondering whether the following two features are available for the clusstree visualisation:

1. Attach a two-argument function to a node characteristic. E.g. use node_alpha + node_alpha_aggr to have the transparency represent something like percentage of patients(one of the columns) in a cluster. This would need both cluster size and number of patients of the cluster.

2. Can there be labels on the nodes on the classic visusalization (not the overlays)?

Thanks a lot in advance, once again the package is awesome.

**Comment by BioSok** [comment]
Thanks for your time, that would be really useful!

**Comment by lazappi** [comment]
I have added an option for additional custom node labels in 7e444c6. You can install that version from GitHub now or it will be in the next CRAN release, hopefully soon.

I want to make it possible to use multiple metadata columns for aesthetics but I think the best way to do that will require a fairly significant rewrite and change to the interface and I don't quite have the time to do that at the moment. I have opened an issue here (#26) with some of my ideas about how that could work.
