### ISSUE TITLE
Using pre-existing seurat object. 

### ISSUE THREAD

**Issue by kasumaz** [lazappi/clustree#30]
Dear Luke Zappia/Alicia Oshlack, 
I am using Seurat V3. I have done some analysis with it. All is set up in the seurat object. There are the pca + tsne cell coordinates on a slot in the object. 
I have had a tough time to take that information and copy into the meta.data. I know this is not 100% an issue with the clustree package. I am just wondering if you ever have some parts of a script that I can use where you took a pre-existing seurat object and organised the meta.data in this way?  
I am very eager to use clustree to add to data I have already. 
The tutorial works. I seem to be unable to expand on the meta.data for running clustree. 
Many thanks 
Kaz

**Comment by lazappi** [comment]
Hi @kasumaz 

Thanks for giving clustree a go!

If you are trying to use the `clustree_overlay` function you shouldn't need to copy the coordinates to the `meta.data` slot, the function will do this for you.

If you just want to know how to do this more generally you might want to look at some of the Seurat documentation such as this page https://satijalab.org/seurat/essential_commands.html or ask on the Seurat GitHub repository.

Hope that helps!

**Comment by kasumaz** [comment]
Hi Apologies for my late reply. I am just finishing off the cell cycle stuff with Seurat and this is the next step. Maybe more slots are filled into the seurat object. I will try to go through Clustree again and comeback when I have issues. 
Regards, Kaz

**Comment by lazappi** [comment]
I'm going to close this issue now but feel free to comment/open a new one if you have more questions 😸.
