### ISSUE TITLE
How to find raw data in the object to plot in_prop   

### ISSUE THREAD

**Issue by JPingLin** [lazappi/clustree#34]
Hi
Not sure if this has been posted before, I am trying to access the data that used to plot in_prop. Can you direct me where to find it? This is the first layer of list titles that I have
test <- clustree(X)
names(test)
[1] "data"        "layers"      "scales"      "mapping"     "theme"      
[6] "coordinates" "facet"       "plot_env"    "labels"    

Thanks!

**Comment by lazappi** [comment]
By default the clustree function returns a ggplot object but you probably want to return a graph object instead. You can then extract the edge information including the in proportion scores.

```r
library(clustree)
library(tidygraph)

graph <- clustree(iris_clusts, prefix = "K", return = "graph")
edges <- graph %>%
    activate("edges") %>%
    as.data.frame()
colnames(edges)
#> [1] "from"       "to"         "from_clust" "to_clust"   "from_K"     "to_K"      
#> [7] "count"      "in_prop"    "width"      "is_core" 
```

**Comment by JPingLin** [comment]
Awesome, thank you so much!
