### ISSUE TITLE
Error if options(stringsAsFactors = FALSE)

### ISSUE THREAD

**Issue by twesleyb** [lazappi/clustree#36]
Using the common option,
```
options(stringsAsFactors = FALSE)
```
causes an error:
> Error in pathAttr(data, length(unique(data$group))) :
Not compatible with requested type: [type=character; target=integer].

```
# Works:
library(clustree)
data("iris_clusts")
clustree(iris_clusts, prefix = "K")

# Won't work:
options(stringsAsFactors = FALSE)
clustree(iris_clusts, prefix = "K")
```

**Comment by lazappi** [comment]
Hi

Thanks for the bug report, I didn't know that setting global options like that would affect what happens inside a package. I guess that's another reason I'm not a fan of them.

I think this might be an issue with the `ggraph` package that `clustree` uses to produce the visualisation so I have reported it there (https://github.com/thomasp85/ggraph/issues/193). I think that package is being actively developed at the moment so hopefully there is a solution soon.

**Comment by thomasp85** [comment]
This is indeed a bug in ggraph that will get fixed. But just as an aside to save you some pain in the future: Don't use `options(stringsAsFactors = FALSE)` as it will make your code non-portable. Either rely on the system default or set it explicitly in each call or use constructors that have different semantics, such as those from tibble or data.table

**Comment by twesleyb** [comment]
Hi Thomas, Thanks for your note, I appreciate your tip!
