### ISSUE TITLE
Customising arrow colour

### ISSUE THREAD

**Issue by liz-is** [lazappi/clustree#45]
Hi,

It doesn't seem like it is possible to customise the colour-coding used for the arrows between nodes, is that correct? I tried `clustree(x) + scale_colour_brewer("Blues")`, but this changed the node colour.

I find the mapping of brighter/lighter colours to higher numbers unintuitive, especially when combined with transparency that is typically higher for darker colours. It would be nice to have the option of a colour scheme that maps darker colours to higher numbers, and perhaps also the option to turn off this colour mapping. 

Thanks for the nice package!

**Comment by lazappi** [comment]
Hi @liz-is 

Thanks for giving **clustree** a go! 😸

You should be able to change the edge colour scale using one of the `scale_edge_colour_X()` functions from the **graph** package. This package is loaded with **clustree** so it should just work.

Thanks for your other comments about the edge colours. Can you provide any examples of what you mean about the differences between colour and transparency? If you come up with a good alternative colour scheme that would be nice to see as well. I have also wondered a bit about whether the edge colours are necessary so it might be useful to be able to turn this off or show it in another way.

Happy to hear any other suggestions you have.

**Comment by liz-is** [comment]
`scale_edge_colour_x` works perfectly, thank you! I used `scale_edge_colour_distiller(direction = 1)` for a scale where darker blue represents higher numbers and lighter blue maps to lower numbers. I see now that you do have an example of using `cale_edge_color_continuous` in the vignette. I must have missed it yesterday, sorry! 

So, personally I find it a bit confusing to have colour mapped to number (with higher = brighter) and transparency mapped to proportion (with higher = less transparent). Low numbers that represent low proportions are mapped to partially transparent dark colours on a white background, ending up as light-ish colours. It can be hard to compare a light purple to a medium green and know which is more "important".  Of course this depends on what features of the data you want to emphasise! And I also think it depends on personal preference, which isn't an issue since I now know how to customise it! :)
