### ISSUE TITLE
How to pick the best resolution option for Seurat clustering

### ISSUE THREAD

**Issue by liuxl18-hku** [lazappi/clustree#46]
Hi,

I currently has a big data set. Pre-process and clustering was done using [Seurat](https://github.com/satijalab/seurat). Now I am trying to use this very cool package to help me pick a better resolution for clustering (actually a bit over-clustering).

Here I tried 10 different resolutions from 1 to 10, and plotted clustree (using sc3_stability). The tree has ten layers representing res=1 to 10 from top to bottom.

Would like to pick ur minds for better interpretation and resolution options.

[clustree_stability.singlet.pc50.pdf](https://github.com/lazappi/clustree/files/4427272/clustree_stability.singlet.pc50.pdf)

Have a good weekend and take care.

bless~

**Comment by lazappi** [comment]
Hi @liuxl18-hku 

Thanks for giving **{clustree}** a go! I don't feel it is appropriate for me to comment too much on specific datasets without knowing the context. My general advice is to look for regions where the clusters are stable and there are few edges crossing between branches. It is also often very useful to look at the expression of important marker genes. I think you may want to try a lower resolution than you have shown here but that is about all I can say about your data.

**Comment by liuxl18-hku** [comment]
@lazappi ,

You are right, thank u.

bless~
