### ISSUE TITLE
strange export of clustree

### ISSUE THREAD

**Issue by RuixiangLiu01** [lazappi/clustree#47]
Hello developer, I met a strange result of `clustree(dataset)`, which dataset is a seurat object

![cluster_res_evaluate](https://user-images.githubusercontent.com/37862626/79428407-b2680580-7ff8-11ea-834d-fc7ac0bc459f.jpg)

So,as you can see many clusters can't traceback.By the way,this is the first time I get this trouble,
any suggestions will be welcome,thanks

**Comment by RuixiangLiu01** [comment]
I have solved this problem,because of my OS didn't support semi-transparency graphics,I use CairoTIFF function to solve.

**Comment by lazappi** [comment]
Thanks for letting us know about the fix! 👍
