### ISSUE TITLE
Labelling nodes with size

### ISSUE THREAD

**Issue by lazappi** [lazappi/clustree#48]
Received via email:

> i´d like to use your package to visualize clusters results.
> 
> I have a question: how to visualize the size of each node?
> My data are not labeled, so I can´t use something like:
> 
> ```r
> countrow <- function(labels) {
>    length(labels)
>    return(length(labels))
> }
> 
> 
> clustree(iris_clusts, prefix = "K", node_label = "Species",
>     node_label_aggr = "countrow")
> ```

**Comment by lazappi** [comment]
Hi

I'm not quite sure what you mean by "unlabelled" but if you have any kind of metadata column you should be able to do something like:

```r
clustree(iris_clusts, prefix = "K", node_label = "{meta_col}", node_label_aggr = "length")
```

However the easiest way would be to use the size variable that is calculated when the tree is built:

```r
clustree(iris_clusts, prefix = "K", node_label = "size")
```

Hope that helps 😸

**Comment by graziano-aglietti-mpf** [comment]
clustree(iris_clusts, prefix = "K", node_label = "size")

this is what I was looking for, thank You
Graziano
