### ISSUE TITLE
Error: Less than two column names matched the prefix: .res but I have ran a few clusters

### ISSUE THREAD

**Issue by klai001** [lazappi/clustree#51]
Hi Developers of Clustree

I have ran find clusters with a few resolutions
 `obj <- FindClusters(object = obj, resolution = seq(0.5,0.6,0.7))` 
this works ok
and then ran clustree

`clustree(obj,prefix = "res.")`

but I got the error 
_Error: Less than two column names matched the prefix: res._

Could you kindly share with me what am I missing out?
I am running Seurat_3.1.5

**Comment by lazappi** [comment]
Hi @klai001 

Thanks for giving **{clustree}** a go! 😸 That error suggests that your prefix is not correct or your metadata columns are named differently. I would suggest you have a look at the columns in the Seurat object and check how they are named.

**Comment by lazappi** [comment]
I'm going to close this now but please comment if this is still an issue.
