### ISSUE TITLE
Understanding Clustree image

### ISSUE THREAD

**Issue by ashokpatowary** [lazappi/clustree#64]
HI @lazappi 

I am trying to use clustree for my single cell RNA seq data for a very small number of cells. I processed the data with seurat. Looking at the clustree plot, it looks at lower resolution there is lots of cross connections. Does it mean those clusters are not stable?

Thanks

![Clustree](https://user-images.githubusercontent.com/42618005/95132675-04225a80-0715-11eb-8a3d-175619b3b74f.png)

**Comment by lazappi** [comment]
Hi @ashokpatowary 

Thanks for giving **clustree** a go! This approach can show you which clusters are similar, but why is much more difficult. For scRNA-seq data I always recommend overlaying the expression of known marker genes and following what the biology tells you. I don't want to do too much interpretation but this looks like a pretty normal tree to me.
