### ISSUE TITLE
cluster with the same cells at different resolutions  have different median genes 

### ISSUE THREAD

**Issue by jingyu9603** [lazappi/clustree#65]
![image](https://user-images.githubusercontent.com/34530948/96673173-78593100-1398-11eb-800a-86fa6201afd3.png)
when I use genes as aesthetics in clustree,I find cluster with the same cells at different resolutions  have different median genes ,As shown in the cluster shown in the blue line .I don't know what's wrong .

**Comment by lazappi** [comment]
Hi @jingyu9603 

Most likely nothing is wrong here. By default we filter out some of the less important edges to make the tree cleaner. If you make the plot again with `prop.filter = 0` you will see all the edges. Hopefully that will explain why the median is different at those resolutions. Hope that helps!

**Comment by jingyu9603** [comment]
Hi @lazappi 

Thank you for your reply !According to your tips ,I make the plot again with `prop.filter = 0`,code as follows
`clustree(seurat.obj, prefix = "SCT_snn_res.",
           node_colour = "CD4", node_colour_aggr = "median",prop.filter = 0)+
    scale_color_gradient2(low="yellow",mid="orange",high="red",midpoint=.3)`
But I get the same plot as follows

![image](https://user-images.githubusercontent.com/34530948/96718822-25549d80-13db-11eb-8a9a-635e15d6ab11.png)

**Comment by lazappi** [comment]
Sorry, my mistake! It should be `prop_filter` (with an underscore), not `prop.filter` (with a dot) 🤦. Can you please try again and see if that is any different? You may also want to try plotting the mean instead of the median, that might show things a bit better.

**Comment by jingyu9603** [comment]
Hi @lazappi 
When I plot again with correct code `prop_filter`,I got the right picture.As you said, the trees like this don't seem very clear .Thank you for your patience .

**Comment by lazappi** [comment]
No problem, sorry for the confusion the first time. Do you have any other questions or are you happy for me to close this issue?
