### ISSUE TITLE
How to access calculated SC3 stabilities?

### ISSUE THREAD

**Issue by mr-september** [lazappi/clustree#66]
For example, when running a range of resolutions, and plotting with `node_colour = "sc3_stability")`, is there any quick way to also report the averaged stability across each row? Or an average weighted by each cluster's sizes?

I know this isn't the only metric to consider, and blindly following math may lead to disastrous results, but the presence of these values may offer some level of guidance.

**Comment by lazappi** [comment]
Hi @mr-september 

There is currently no way to automatically plot an average SC3 stability for each resolution but you should be able to get the values which you could then add to the plot or look at in some other way. By default `clustree()` returns a `ggplot` object containing the plot but you can also get a `tbl_graph` object by setting `return = "graph"`. This is the graph object used to create the plot and should contain the calculated SC3 stability for each node. From that it should be easy enough to calculate an average by resolution.

```r
library(clustree)
library(tidygraph)

graph <- clustree(nba_clusts, prefix = "K", return = "graph")
graph %>%
	activate(nodes) %>%
	as.data.frame() %>%
	group_by(K) %>%
	summarise(average_stability = mean(sc3_stability))
```

**Comment by mr-september** [comment]
Hi @lazappi

Thanks for the guidance! I'm still having some trouble, though. I'm primarily using Seurat objects, with its default Louvain clustering.

Only way I could get it to run was to remove the `prefix=...` parameter entirely, anything else would return `Error: Less than two column names matched the prefix: ...`

Similarly, I had to remove `group_by(K) %>%` lower down.

However, now it only reports one stability. Is this because `group_by(K) %>%` was separating clusters into 'bins', so now it's averaging across the entire `clustree`? If so, how might I be able to fix this?

**Comment by lazappi** [comment]
Finding a prefix for `Seurat` objects can be a bit tricky so using the defaults is probably easiest (if it works).

The grouping is failing because you have a different column name. Have a look at the output after the `as.data.frame()` step to see what the column is called, probably something like `seurat_rna_`.

**Comment by mr-september** [comment]
Thank you for the tip!

For future Googlers, it ended up being
`group_by(RNA_snn_res.)`

**Comment by mr-september** [comment]
Sorry to bother again, but I just tried today with SCTransform instead of scran (back at the normalization step), but this time I'm getting a very different output after the `as.data.frame()` step:
![image](https://user-images.githubusercontent.com/45350177/102437203-e3a44400-4065-11eb-93e3-c8cf576601ab.png)
What would the grouping be in this case? 
I was still able to generate a normal-looking Clustree plot with `clustree(data_transcripts_seurat_PCA1, node_colour = "sc3_stability")`

**Comment by lazappi** [comment]
Hmmm... I'm not sure exactly what is going on here but I'm guessing that using **scTransform** has changed the object in some way. It might be useful to see what the graph object directly from `clustree()` looks like. It would also be great if you could try and replicate this using the example dataset in **Seurat**. Then if you post the commands you used here I can try look into it locally.

**Comment by mr-september** [comment]
Sorry about that, it seems to have arisen from a contaminated environment. After starting fresh, the problem is gone, and the correct prefix is indeed `SCT_snn_res.`
