### ISSUE TITLE
Using clustree with CATALYST::cluster() output

### ISSUE THREAD

**Issue by antoine4ucsd** [lazappi/clustree#67]
Hello
I am working on flow data and I am trying to plot the resulting cluster tree from the output:
`sce <- CATALYST::cluster(sce, features = "type",
               xdim = 20, ydim = 20, maxK = 140, seed = 1234)
`
sce
class: SingleCellExperiment 
dim: 9 42990473 
metadata(4): experiment_info cluster_codes SOM_codes delta_area
assays(2): counts exprs
rownames(9): PD-1 CD3 ... CD8 CD4
rowData names(4): channel_name marker_name marker_class used_for_clustering
colnames: NULL
colData names(4): sample_id condition patient_id cluster_id
reducedDimNames(0):
altExpNames(0):

I can't figure out how to run clusttree (prefix?)
all ideas are welcome

thanks much!

**Comment by lazappi** [comment]
Hi @antoine4ucsd 

I'm not familiar with the `CATALYST::cluster()` function so I don't know what it returns but to use **clustree** you will need a series of columns in `colData(sce)` that contain the clustering labels for each resolution you want to plot. These should be named something like "prefix_X" where "prefix_" is the same for all columns and "X" gives the resolution. You can then call the `clustree()` function like `clustree(sce, prefix = "prefix_", ...)`.

Hope that helps 😸

**Comment by antoine4ucsd** [comment]
Thank you 

a
