### ISSUE TITLE
How to use Seurat object directly in Clustree ?

### ISSUE THREAD

**Issue by ahmadsam66** [lazappi/clustree#69]
Hey,

I am new in using Seurat and Clustree, I have performed some analysis on standard Seurat vignette based on following link and below codes: 
https://satijalab.org/seurat/articles/pbmc3k_tutorial.html
```
library(dplyr)
library(Seurat)
library(patchwork)

# Load the PBMC dataset
pbmc.data <- Read10X(data.dir = "../data/pbmc3k/filtered_gene_bc_matrices/hg19/")
# Initialize the Seurat object with the raw (non-normalized data).
pbmc <- CreateSeuratObject(counts = pbmc.data, project = "pbmc3k", min.cells = 3, min.features = 200)
pbmc

pbmc[["percent.mt"]] <- PercentageFeatureSet(pbmc, pattern = "^MT-")

pbmc <- subset(pbmc, subset = nFeature_RNA > 200 & nFeature_RNA < 2500 & percent.mt < 5)

pbmc <- NormalizeData(pbmc, normalization.method = "LogNormalize", scale.factor = 10000)
pbmc <- NormalizeData(pbmc)
pbmc <- FindVariableFeatures(pbmc, selection.method = "vst", nfeatures = 2000)
all.genes <- rownames(pbmc)
pbmc <- ScaleData(pbmc, features = all.genes)
pbmc <- RunPCA(pbmc, features = VariableFeatures(object = pbmc))
pbmc <- FindNeighbors(pbmc, dims = 1:10)

for ( i in c(0.3,0.5,0.7,0.9) )
{
pbmc <- FindClusters(pbmc, resolution = i)
}
```

How can I make Clustree plot for above **PMBC** object with different resolutions? 

cheers.

**Comment by lazappi** [comment]
HI @ahmadsam66 

Thanks for giving **clustree** a go 🎉! The first thing to try is simply running `clustree(pbmc)`. If that doesn't work most likely you will need to set some additional parameters (probably `prefix`). The error message should be helpful for finding what the problem is.

**Comment by lazappi** [comment]
@ahmadsam66 Did you have any luck with this?

**Comment by ahmadsam66** [comment]
Hi Luke,

It was not work with `clustree(pbmc)`, is it possible to repeat the code of clustree for it ? , the below link is Seurat vignette :
https://satijalab.org/seurat/articles/pbmc3k_tutorial.html

I would appreciate if you could solve it.

**Comment by lazappi** [comment]
Hi @ahmadsam66 

I can't really help without seeing what code you are running and the error message. Please post those and I may be able to help further. Please also try to address what is in the error message first (most likely setting the `prefix` argument correctly as mentioned above).

**Comment by lazappi** [comment]
Hi @ahmadsam66. Were you able to get this working?

**Comment by lazappi** [comment]
Hmmm...that's strange. Can you please share the code you used to get to this point? (please use ` ``` ` to format code chunks rather than posting images)
