### ISSUE TITLE
Selecting assay and expression type for Seurat objects

### ISSUE THREAD

**Issue by TrumanZYX** [lazappi/clustree#70]
Thanks for your clustree. But i have some questions.
When i use SCT to deal with my single cell dataset in seurat. My Gene expression matrix at this time is in SCT assay not in RNA assay. So When i want to use gene in clustree, I want to know which Gene expression matrix the clustree would use. ( SCT assay or RNA assay).
2. I want to know which Gene expression matrix will use (data OR count)  ------ (data is  normalize Gene expression matrix     and    count is not  normalize Gene expression matrix ) We should use data not count( seurat author recommond us to use in RNA assay). 
3. When we use SCT to integret different dataset in seuart. The seurat recommed to use RNA assay not SCT assay. So at the same time, we can choose which assay we use in seurat?
Thanks for you help.

**Comment by lazappi** [comment]
Hi @TrumanZYX 

Thanks for giving **clustree** a go! Please have a look at the documentation for the `clustree()` function using `?clustree`. You will see information about the various arguments including `exprs` and `assay` which you can use to select the matrix which gene information is extracted from.
