### ISSUE TITLE
Node text alignment

### ISSUE THREAD

**Issue by denertekin** [lazappi/clustree#74]
Hi, 

I have a dataset with ~90_ clusters and am using clustree to find optimal resolutions. I'm struggling with plotting a little as it looks very cluttered with some nodes overlapping. I was wondering if there is a way to align the node_text either below or above nodes? 
or if you have any recommendation on how to plot datasets with higher number of clusters? 

Thank you very much ! 
Deniz

**Comment by lazappi** [comment]
Hi @denertekin

Thanks for giving **clustree** a go! You are right that things often get messy when there are a lot of clusters. Could you please post an example of what the plot looks like currently, that could help with suggesting a solution? I'm not sure that there is an easy way to adjust the node text position but we might be able to come up with something that works in your case. If you want to try some things my first suggestions would be making the node points smaller or increasing the plot size.
