### ISSUE TITLE
Allow plotting nodes as pie charts

### ISSUE THREAD

**Issue by mdstobbe** [lazappi/clustree#78]
Good afternoon,

The clustree R package has been very useful, thank you for providing it!

I was wondering if there would be an easy way to replace the circles in the clustree with piediagrams showing the distribution of the samples, for example the cell types in the case of single cell data. Or perhaps this could be added?

Kind regards,
Miranda

**Comment by lazappi** [comment]
Hi @mdstobbe 

Thanks for giving **{clustree}** a go! Can you please explain what a "piediagram" is? I haven't heard that term before. Thanks!

**Comment by mdstobbe** [comment]
Good morning!

Yes, of course, sorry.

We are looking to make something like this (file:///Users/mdstobbe/Downloads/pcbi.1007496.s001-3.pdf):
[cid:0d906f0b-4876-4b96-910f-3db25509c081]

We used clustree for constructing the tree, but we manually replaced the circles with the piecharts.

Kind regards,
Miranda
________________________________

**Comment by lazappi** [comment]
I can't see the file but I think I know what you mean. I don't have plans to add this as a feature and I think it would be very difficult to do.

The closest thing would be to write a function which calculates the proportion of samples in each cluster belonging to a particular sample or how "pure" the cluster is in terms of samples and use that to colour each node but that's probably a bit less effective than a pie chart.

**Comment by mdstobbe** [comment]
Okay, thank you for letting me know!

I will continue my search for a solution.

Kind regards,
Miranda
________________________________
