### ISSUE TITLE
Rotate node labels

### ISSUE THREAD

**Issue by kvittingseerup** [lazappi/clustree#79]
Thanks for an amazing tool.

I'm currently working on a clustree using named clusters but have run into the problem that the names then start to overlap. Would it be possible to enable rotation of node labels?

Cheers
Kristoffer

**Comment by lazappi** [comment]
Do you have an example you can share just so I'm sure I know what you mean?

I think this should be possible though. I don't have a lot of capacity to work on **{clustree}** at the moment though so not sure I can get to this any time soon. I would be more than happy to accept a pull request, I can explain what would need to be done if that helps.

**Comment by kvittingseerup** [comment]
Nice idea! I've just pushed [on](https://github.com/lazappi/clustree/pull/80).

**Comment by lazappi** [comment]
Thanks! I will leave this open until the PR is merged.
