### ISSUE TITLE
Error for Seurat

### ISSUE THREAD

**Issue by PrashINRA** [lazappi/clustree#85]
Hi, 
I was successfully running clustree for obtaining clusters at different resolutions from Seurat.
Just updated the Seurat, ggplot2, etc. Now it shows error- Error in check.length(gparname) : 
  'gpar' element 'lwd' must not be length 0.

My code for Seurat object: 

 Seu<- FindClusters(Seu, resolution =  seq(from = 0.1, to = 0.7, by = 0.1))
clust_seurat <- Seu@meta.data %>% dplyr::select(dplyr::contains("RNA_snn_res."))
clustree::clustree(clust_seurat, prefix="RNA_snn_res.")

**Comment by lazappi** [comment]
This is a duplicated of #82, please check the discussion there.
