### ISSUE TITLE
Error: could not find function "try_fetch"

### ISSUE THREAD

**Issue by MANZHAOHUI** [lazappi/clustree#87]
Hi, 
Upon running clustree, I keep getting the error 
"Error in try_fetch(utils::getFromNamespace(algorithm, "igraph"), error = function(cnd) { : could not find function "try_fetch""
I reinstalled 'rlang', 'ggraph' and still got this.  I am wondering if you could give me and advice in regards to it. 
Thank you.

**Comment by MANZHAOHUI** [comment]
I am dealing with single cell seurat object, using umap as reduction method with the codes as below:
combined.integrated <- RunUMAP(combined.integrated, dims = 1:30)
combined.integrated <- FindNeighbors(combined.integrated, reduction = "umap", dims = 1:2)
combined.int.clustree <- FindClusters(
  object = combined.integrated,
  method = "igraph", 
  resolution = c(0.1, 0.2, 0.3, 0.4, 0.5, 0.6)
)
combined.int.clustree@meta.data [1:3, ]
  orig.ident nCount_RNA nFeature_RNA    Sex age sampID
01_38_AAACCCACAGTGTACT-1         PD       1696         1010 Female  80  01_38
01_38_AAACCCAGTTGGGATG-1         PD      12040         3389 Female  80  01_38
01_38_AAACCCATCCAGCACG-1         PD       2839         1540 Female  80  01_38
                         percent.mt PMI nCount_SCT nFeature_SCT predicted.id
01_38_AAACCCACAGTGTACT-1   4.126625 7.5       3471         1047        Oligo
01_38_AAACCCAGTTGGGATG-1   1.978344 7.5       4514         2214        Oligo
01_38_AAACCCATCCAGCACG-1   6.519592 7.5       3513         1539        Oligo
                         prediction.score.Inh prediction.score.Exc
01_38_AAACCCACAGTGTACT-1                    0                    0
01_38_AAACCCAGTTGGGATG-1                    0                    0
01_38_AAACCCATCCAGCACG-1                    0                    0
                         prediction.score.Oligo prediction.score.Astro
01_38_AAACCCACAGTGTACT-1                      1                      0
01_38_AAACCCAGTTGGGATG-1                      1                      0
01_38_AAACCCATCCAGCACG-1                      1                      0
                         prediction.score.Micro prediction.score.OPC
01_38_AAACCCACAGTGTACT-1                      0                    0
01_38_AAACCCAGTTGGGATG-1                      0                    0
01_38_AAACCCATCCAGCACG-1                      0                    0
                         prediction.score.Endo prediction.score.VLMC
01_38_AAACCCACAGTGTACT-1                     0                     0
01_38_AAACCCAGTTGGGATG-1                     0                     0
01_38_AAACCCATCCAGCACG-1                     0                     0
                         prediction.score.max adjusted.prediction.score.max
01_38_AAACCCACAGTGTACT-1                    1                             1
01_38_AAACCCAGTTGGGATG-1                    1                             1
01_38_AAACCCATCCAGCACG-1                    1                             1
                         integrated_snn_res.0.1 integrated_snn_res.0.2
01_38_AAACCCACAGTGTACT-1                      0                     10
01_38_AAACCCAGTTGGGATG-1                      3                     15
01_38_AAACCCATCCAGCACG-1                      2                      9
                         integrated_snn_res.0.3 integrated_snn_res.0.4
01_38_AAACCCACAGTGTACT-1                      1                     36
01_38_AAACCCAGTTGGGATG-1                      5                     39
01_38_AAACCCATCCAGCACG-1                     11                     13
                         integrated_snn_res.0.5 integrated_snn_res.0.6
01_38_AAACCCACAGTGTACT-1                     13                      6
01_38_AAACCCAGTTGGGATG-1                      2                     36
01_38_AAACCCATCCAGCACG-1                      9                      9
                         seurat_clusters
01_38_AAACCCACAGTGTACT-1               6
01_38_AAACCCAGTTGGGATG-1              36
01_38_AAACCCATCCAGCACG-1               9

cluster_tree <- clustree(combined.int.clustree,prefix = "integrated_snn_res.")

all the steps worked except for the last one 'clustree(combined.int.clustree,prefix = "integrated_snn_res.")'
the error is 
"Error in try_fetch(utils::getFromNamespace(algorithm, "igraph"), error = function(cnd) { :
  could not find function "try_fetch" "

thank you.

**Comment by lazappi** [comment]
Hi @MANZHAOHUI 

This looks like a problem with your installation of the **{igraph}** package. I found try re-installing that and seeing if that helps. If not you may have to ask the package developers, I don't think this is an issue with **{clustree}**.
