### ISSUE TITLE
Error: Less than two column names matched the prefix: SCT_snn_res.

### ISSUE THREAD

**Issue by lc-hhh** [lazappi/clustree#90]
clustree(tissue,prefix = "SCT_snn_res.",assay = "SCT")
Error: Less than two column names matched the prefix: SCT_snn_res.

but when I run following statement there is no problem
tissue <- FindClusters(tissue, resolution = c(0.1,0.4,0.6))

I just want to see the clustering of different resolutions, does anyone know how to solve this problem?

**Comment by lazappi** [comment]
This happens when the columns from the clustering don't match the prefix you have set. Please see #51, #86.
