### ISSUE TITLE
Prepare for upcoming Seurat v5 release

### ISSUE THREAD

**Issue by Gesmira** [lazappi/clustree#93]
I am opening this issue as a notification because `clustree` is listed [here](https://cran.r-project.org/web/packages/Seurat/index.html) as a package that relies (depends/imports/suggests) on Seurat. As you may know, we recently released Seurat v5 as a beta in March of this year, with new updates for spatial, multimodal, and massively scalable analysis. For more information on updates and improvements, check out our website https://satijalab.org/seurat/.
We are now preparing to release Seurat v5 to CRAN, and plan to submit it on October 23rd. While we have tried our best to keep things backward-compatible, it is possible that updates to Seurat and SeuratObject might break your existing functionality or tests. We wanted to reach out before the new version is on CRAN, so that there's time to report issues/incompatibilities and prepare you for any changes in your code base that might be necessary.

We apologize for any disruption or inconvenience, but hope that the improvements to Seurat v5 will benefit your users going forward.
To test the upcoming release, you can install Seurat from the `seurat5` branch using the instructions available on this page: https://satijalab.org/seurat/articles/install.

Thank you!
Seurat v5 team

**Comment by lazappi** [comment]
Hi @Gesmira. Thanks for the notification. I have done a quick check and it looks like things might break with the new version 😿. Is there any documentation about what has been changed and what changes developers need to make for compatibility?

**Comment by saketkc** [comment]
Hi @lazappi,
Seuratv5 will make its way to CRAN soon and reverse-dependency checks indicate following tests will fail:

```
Running the tests in ‘tests/testthat.R’ failed.
Last 13 lines of output:
    1. ├─testthat::expect_warning(...) at test-clustree.R:165:4
    2. │ └─testthat:::quasi_capture(...)
    3. │   ├─testthat (local) .capture(...)
    4. │   │ └─base::withCallingHandlers(...)
    5. │   └─rlang::eval_bare(quo_get_expr(.quo), quo_get_env(.quo))
    6. ├─clustree::clustree(...)
    7. └─clustree:::clustree.Seurat(...)
    8.   ├─Seurat::FetchData(x, vars = node_aes_value, slot = exprs)
    9.   └─SeuratObject:::FetchData.Seurat(x, vars = node_aes_value, slot = exprs)
   10.     ├─SeuratObject::FetchData(...)
   11.     └─SeuratObject:::FetchData.Assay5(...)
   12. ```
``` 
One potential fix would be to do:
```r
op <- options(Seurat.object.assay.brackets = "v3")
on.exit(options(op), add = TRUE)
```
so that your users will stick to V3 assays. But it is possible you might have to update your accessor methods to be compatible with Seurat5 going ahead.

**Comment by lazappi** [comment]
Hi @saketkc. Yes, I am aware the tests are currently failing. I just haven't had a chance to make the changes yet.

As a sidenote, it would have been great if you sent out these messages in March when you say the changes were announced rather than waiting a few weeks before you want to do the release.

**Comment by lazappi** [comment]
I have pushed a version to the `develop` branch that should be compatible. I am happy to release this on CRAN but wanted to check if there are any timelines etc. I should be available of first.
