### ISSUE TITLE
Error in clustree.matrix(clusterings, prefix, metadata = metadata, ...) :    Assertion on 'x' failed: Contains missing values (row 23366, col 1).

### ISSUE THREAD

**Issue by LiHangzls** [lazappi/clustree#98]
this is code:
pbmc_list %>%     RunUMAP(dim=1:20) %>%
    FindNeighbors(dim=1:20) %>% FindClusters(resolution =c(0.1,0.2,0.4,0.6,0.8))-> pbmc_list 
  library(clustree)
  pbmc_list@meta.data %>% 
    dplyr::select(starts_with("integrated_snn_res"))  %>% 
    dplyr::mutate(integrated_snn_res.0.0=0)%>% 
    clustree( prefix = "integrated_snn_res")
this is error:
Error in clustree.matrix(clusterings, prefix, metadata = metadata, ...) : 
  Assertion on 'x' failed: Contains missing values (row 23366, col 1).

**Comment by lazappi** [comment]
It's a bit hard to say why from the provided code but the error suggests there is a missing value in the provided data. Please check you input data to see why there are missing values.

**Comment by lazappi** [comment]
Closing this issue but please reopen if you have further questions
