### ISSUE TITLE
Missing edges in clustering tree

### ISSUE THREAD

**Issue by wbvguo** [lazappi/clustree#99]
Dear clustree maintainer,

Thank you for maintaining this tool. I tried this tool on my single cell RNA-seq data with varying clustering resolution. But I found some strange phenomenon about the output figure. please see below:

![clustree_unexpected_res](https://github.com/lazappi/clustree/assets/31968837/ed0303c0-afbe-4b01-ae76-ce0dd48ea7fc)

Strange place: there are some nodes that has no arrow connecting to the next layer, such as the node 8 in the first layer and node 18 in the third layer. 

Since each layer here is a specific clustering resolution on the same cell population, so I would expect the nodes will either merge or split between layers, there should not be any node that has no connection to the next layer. May I ask if you could provide some wisdoms on this issue?

Thanks,

**Comment by lazappi** [comment]
Hi @wbvguo 

By default filters are applied to avoid showing edges representing very few samples. I believe this is why some of your nodes appear to be disconnected. You can turn these filters off by setting the arguments in the `clustree()` function to `0.0`.

**Comment by lazappi** [comment]
I am closing this issue now, please reopen if you have further questions.
